package nme.ui;


#if flash
@:native ("flash.ui.Keyboard")
extern class Keyboard {
	@:require(flash10_1) static var A : UInt;
	@:require(flash10_1) static var ALTERNATE : UInt;
	@:require(flash10_2) static var AUDIO : UInt;
	@:require(flash10_1) static var B : UInt;
	@:require(flash10_2) static var BACK : UInt;
	@:require(flash10_1) static var BACKQUOTE : UInt;
	@:require(flash10_1) static var BACKSLASH : UInt;
	static var BACKSPACE : UInt;
	@:require(flash10_2) static var BLUE : UInt;
	@:require(flash10_1) static var C : UInt;
	static var CAPS_LOCK : UInt;
	@:require(flash10_2) static var CHANNEL_DOWN : UInt;
	@:require(flash10_2) static var CHANNEL_UP : UInt;
	@:require(flash10_1) static var COMMA : UInt;
	@:require(flash10_1) static var COMMAND : UInt;
	static var CONTROL : UInt;
	@:require(flash10_1) static var CharCodeStrings : Array<Dynamic>;
	@:require(flash10_1) static var D : UInt;
	static var DELETE : UInt;
	static var DOWN : UInt;
	@:require(flash10_2) static var DVR : UInt;
	@:require(flash10_1) static var E : UInt;
	static var END : UInt;
	static var ENTER : UInt;
	@:require(flash10_1) static var EQUAL : UInt;
	static var ESCAPE : UInt;
	@:require(flash10_2) static var EXIT : UInt;
	@:require(flash10_1) static var F : UInt;
	static var F1 : UInt;
	static var F10 : UInt;
	static var F11 : UInt;
	static var F12 : UInt;
	static var F13 : UInt;
	static var F14 : UInt;
	static var F15 : UInt;
	static var F2 : UInt;
	static var F3 : UInt;
	static var F4 : UInt;
	static var F5 : UInt;
	static var F6 : UInt;
	static var F7 : UInt;
	static var F8 : UInt;
	static var F9 : UInt;
	@:require(flash10_2) static var FAST_FORWARD : UInt;
	@:require(flash10_1) static var G : UInt;
	@:require(flash10_2) static var GREEN : UInt;
	@:require(flash10_2) static var GUIDE : UInt;
	@:require(flash10_1) static var H : UInt;
	@:require(flash10_2) static var HELP : UInt;
	static var HOME : UInt;
	@:require(flash10_1) static var I : UInt;
	@:require(flash10_2) static var INFO : UInt;
	@:require(flash10_2) static var INPUT : UInt;
	static var INSERT : UInt;
	@:require(flash10_1) static var J : UInt;
	@:require(flash10_1) static var K : UInt;
	@:require(flash10_1) static var KEYNAME_BEGIN : String;
	@:require(flash10_1) static var KEYNAME_BREAK : String;
	@:require(flash10_1) static var KEYNAME_CLEARDISPLAY : String;
	@:require(flash10_1) static var KEYNAME_CLEARLINE : String;
	@:require(flash10_1) static var KEYNAME_DELETE : String;
	@:require(flash10_1) static var KEYNAME_DELETECHAR : String;
	@:require(flash10_1) static var KEYNAME_DELETELINE : String;
	@:require(flash10_1) static var KEYNAME_DOWNARROW : String;
	@:require(flash10_1) static var KEYNAME_END : String;
	@:require(flash10_1) static var KEYNAME_EXECUTE : String;
	@:require(flash10_1) static var KEYNAME_F1 : String;
	@:require(flash10_1) static var KEYNAME_F10 : String;
	@:require(flash10_1) static var KEYNAME_F11 : String;
	@:require(flash10_1) static var KEYNAME_F12 : String;
	@:require(flash10_1) static var KEYNAME_F13 : String;
	@:require(flash10_1) static var KEYNAME_F14 : String;
	@:require(flash10_1) static var KEYNAME_F15 : String;
	@:require(flash10_1) static var KEYNAME_F16 : String;
	@:require(flash10_1) static var KEYNAME_F17 : String;
	@:require(flash10_1) static var KEYNAME_F18 : String;
	@:require(flash10_1) static var KEYNAME_F19 : String;
	@:require(flash10_1) static var KEYNAME_F2 : String;
	@:require(flash10_1) static var KEYNAME_F20 : String;
	@:require(flash10_1) static var KEYNAME_F21 : String;
	@:require(flash10_1) static var KEYNAME_F22 : String;
	@:require(flash10_1) static var KEYNAME_F23 : String;
	@:require(flash10_1) static var KEYNAME_F24 : String;
	@:require(flash10_1) static var KEYNAME_F25 : String;
	@:require(flash10_1) static var KEYNAME_F26 : String;
	@:require(flash10_1) static var KEYNAME_F27 : String;
	@:require(flash10_1) static var KEYNAME_F28 : String;
	@:require(flash10_1) static var KEYNAME_F29 : String;
	@:require(flash10_1) static var KEYNAME_F3 : String;
	@:require(flash10_1) static var KEYNAME_F30 : String;
	@:require(flash10_1) static var KEYNAME_F31 : String;
	@:require(flash10_1) static var KEYNAME_F32 : String;
	@:require(flash10_1) static var KEYNAME_F33 : String;
	@:require(flash10_1) static var KEYNAME_F34 : String;
	@:require(flash10_1) static var KEYNAME_F35 : String;
	@:require(flash10_1) static var KEYNAME_F4 : String;
	@:require(flash10_1) static var KEYNAME_F5 : String;
	@:require(flash10_1) static var KEYNAME_F6 : String;
	@:require(flash10_1) static var KEYNAME_F7 : String;
	@:require(flash10_1) static var KEYNAME_F8 : String;
	@:require(flash10_1) static var KEYNAME_F9 : String;
	@:require(flash10_1) static var KEYNAME_FIND : String;
	@:require(flash10_1) static var KEYNAME_HELP : String;
	@:require(flash10_1) static var KEYNAME_HOME : String;
	@:require(flash10_1) static var KEYNAME_INSERT : String;
	@:require(flash10_1) static var KEYNAME_INSERTCHAR : String;
	@:require(flash10_1) static var KEYNAME_INSERTLINE : String;
	@:require(flash10_1) static var KEYNAME_LEFTARROW : String;
	@:require(flash10_1) static var KEYNAME_MENU : String;
	@:require(flash10_1) static var KEYNAME_MODESWITCH : String;
	@:require(flash10_1) static var KEYNAME_NEXT : String;
	@:require(flash10_1) static var KEYNAME_PAGEDOWN : String;
	@:require(flash10_1) static var KEYNAME_PAGEUP : String;
	@:require(flash10_1) static var KEYNAME_PAUSE : String;
	@:require(flash10_1) static var KEYNAME_PREV : String;
	@:require(flash10_1) static var KEYNAME_PRINT : String;
	@:require(flash10_1) static var KEYNAME_PRINTSCREEN : String;
	@:require(flash10_1) static var KEYNAME_REDO : String;
	@:require(flash10_1) static var KEYNAME_RESET : String;
	@:require(flash10_1) static var KEYNAME_RIGHTARROW : String;
	@:require(flash10_1) static var KEYNAME_SCROLLLOCK : String;
	@:require(flash10_1) static var KEYNAME_SELECT : String;
	@:require(flash10_1) static var KEYNAME_STOP : String;
	@:require(flash10_1) static var KEYNAME_SYSREQ : String;
	@:require(flash10_1) static var KEYNAME_SYSTEM : String;
	@:require(flash10_1) static var KEYNAME_UNDO : String;
	@:require(flash10_1) static var KEYNAME_UPARROW : String;
	@:require(flash10_1) static var KEYNAME_USER : String;
	@:require(flash10_1) static var L : UInt;
	@:require(flash10_2) static var LAST : UInt;
	static var LEFT : UInt;
	@:require(flash10_1) static var LEFTBRACKET : UInt;
	@:require(flash10_2) static var LIVE : UInt;
	@:require(flash10_1) static var M : UInt;
	@:require(flash10_2) static var MASTER_SHELL : UInt;
	@:require(flash10_2) static var MENU : UInt;
	@:require(flash10_1) static var MINUS : UInt;
	@:require(flash10_1) static var N : UInt;
	@:require(flash10_2) static var NEXT : UInt;
	@:require(flash10_1) static var NUMBER_0 : UInt;
	@:require(flash10_1) static var NUMBER_1 : UInt;
	@:require(flash10_1) static var NUMBER_2 : UInt;
	@:require(flash10_1) static var NUMBER_3 : UInt;
	@:require(flash10_1) static var NUMBER_4 : UInt;
	@:require(flash10_1) static var NUMBER_5 : UInt;
	@:require(flash10_1) static var NUMBER_6 : UInt;
	@:require(flash10_1) static var NUMBER_7 : UInt;
	@:require(flash10_1) static var NUMBER_8 : UInt;
	@:require(flash10_1) static var NUMBER_9 : UInt;
	@:require(flash10_1) static var NUMPAD : UInt;
	static var NUMPAD_0 : UInt;
	static var NUMPAD_1 : UInt;
	static var NUMPAD_2 : UInt;
	static var NUMPAD_3 : UInt;
	static var NUMPAD_4 : UInt;
	static var NUMPAD_5 : UInt;
	static var NUMPAD_6 : UInt;
	static var NUMPAD_7 : UInt;
	static var NUMPAD_8 : UInt;
	static var NUMPAD_9 : UInt;
	static var NUMPAD_ADD : UInt;
	static var NUMPAD_DECIMAL : UInt;
	static var NUMPAD_DIVIDE : UInt;
	static var NUMPAD_ENTER : UInt;
	static var NUMPAD_MULTIPLY : UInt;
	static var NUMPAD_SUBTRACT : UInt;
	@:require(flash10_1) static var O : UInt;
	@:require(flash10_1) static var P : UInt;
	static var PAGE_DOWN : UInt;
	static var PAGE_UP : UInt;
	@:require(flash10_2) static var PAUSE : UInt;
	@:require(flash10_1) static var PERIOD : UInt;
	@:require(flash10_2) static var PLAY : UInt;
	@:require(flash10_2) static var PREVIOUS : UInt;
	@:require(flash10_1) static var Q : UInt;
	@:require(flash10_1) static var QUOTE : UInt;
	@:require(flash10_1) static var R : UInt;
	@:require(flash10_2) static var RECORD : UInt;
	@:require(flash10_2) static var RED : UInt;
	@:require(flash10_2) static var REWIND : UInt;
	static var RIGHT : UInt;
	@:require(flash10_1) static var RIGHTBRACKET : UInt;
	@:require(flash10_1) static var S : UInt;
	@:require(flash10_2) static var SEARCH : UInt;
	@:require(flash10_1) static var SEMICOLON : UInt;
	@:require(flash10_2) static var SETUP : UInt;
	static var SHIFT : UInt;
	@:require(flash10_2) static var SKIP_BACKWARD : UInt;
	@:require(flash10_2) static var SKIP_FORWARD : UInt;
	@:require(flash10_1) static var SLASH : UInt;
	static var SPACE : UInt;
	@:require(flash10_2) static var STOP : UInt;
	@:require(flash10_1) static var STRING_BEGIN : String;
	@:require(flash10_1) static var STRING_BREAK : String;
	@:require(flash10_1) static var STRING_CLEARDISPLAY : String;
	@:require(flash10_1) static var STRING_CLEARLINE : String;
	@:require(flash10_1) static var STRING_DELETE : String;
	@:require(flash10_1) static var STRING_DELETECHAR : String;
	@:require(flash10_1) static var STRING_DELETELINE : String;
	@:require(flash10_1) static var STRING_DOWNARROW : String;
	@:require(flash10_1) static var STRING_END : String;
	@:require(flash10_1) static var STRING_EXECUTE : String;
	@:require(flash10_1) static var STRING_F1 : String;
	@:require(flash10_1) static var STRING_F10 : String;
	@:require(flash10_1) static var STRING_F11 : String;
	@:require(flash10_1) static var STRING_F12 : String;
	@:require(flash10_1) static var STRING_F13 : String;
	@:require(flash10_1) static var STRING_F14 : String;
	@:require(flash10_1) static var STRING_F15 : String;
	@:require(flash10_1) static var STRING_F16 : String;
	@:require(flash10_1) static var STRING_F17 : String;
	@:require(flash10_1) static var STRING_F18 : String;
	@:require(flash10_1) static var STRING_F19 : String;
	@:require(flash10_1) static var STRING_F2 : String;
	@:require(flash10_1) static var STRING_F20 : String;
	@:require(flash10_1) static var STRING_F21 : String;
	@:require(flash10_1) static var STRING_F22 : String;
	@:require(flash10_1) static var STRING_F23 : String;
	@:require(flash10_1) static var STRING_F24 : String;
	@:require(flash10_1) static var STRING_F25 : String;
	@:require(flash10_1) static var STRING_F26 : String;
	@:require(flash10_1) static var STRING_F27 : String;
	@:require(flash10_1) static var STRING_F28 : String;
	@:require(flash10_1) static var STRING_F29 : String;
	@:require(flash10_1) static var STRING_F3 : String;
	@:require(flash10_1) static var STRING_F30 : String;
	@:require(flash10_1) static var STRING_F31 : String;
	@:require(flash10_1) static var STRING_F32 : String;
	@:require(flash10_1) static var STRING_F33 : String;
	@:require(flash10_1) static var STRING_F34 : String;
	@:require(flash10_1) static var STRING_F35 : String;
	@:require(flash10_1) static var STRING_F4 : String;
	@:require(flash10_1) static var STRING_F5 : String;
	@:require(flash10_1) static var STRING_F6 : String;
	@:require(flash10_1) static var STRING_F7 : String;
	@:require(flash10_1) static var STRING_F8 : String;
	@:require(flash10_1) static var STRING_F9 : String;
	@:require(flash10_1) static var STRING_FIND : String;
	@:require(flash10_1) static var STRING_HELP : String;
	@:require(flash10_1) static var STRING_HOME : String;
	@:require(flash10_1) static var STRING_INSERT : String;
	@:require(flash10_1) static var STRING_INSERTCHAR : String;
	@:require(flash10_1) static var STRING_INSERTLINE : String;
	@:require(flash10_1) static var STRING_LEFTARROW : String;
	@:require(flash10_1) static var STRING_MENU : String;
	@:require(flash10_1) static var STRING_MODESWITCH : String;
	@:require(flash10_1) static var STRING_NEXT : String;
	@:require(flash10_1) static var STRING_PAGEDOWN : String;
	@:require(flash10_1) static var STRING_PAGEUP : String;
	@:require(flash10_1) static var STRING_PAUSE : String;
	@:require(flash10_1) static var STRING_PREV : String;
	@:require(flash10_1) static var STRING_PRINT : String;
	@:require(flash10_1) static var STRING_PRINTSCREEN : String;
	@:require(flash10_1) static var STRING_REDO : String;
	@:require(flash10_1) static var STRING_RESET : String;
	@:require(flash10_1) static var STRING_RIGHTARROW : String;
	@:require(flash10_1) static var STRING_SCROLLLOCK : String;
	@:require(flash10_1) static var STRING_SELECT : String;
	@:require(flash10_1) static var STRING_STOP : String;
	@:require(flash10_1) static var STRING_SYSREQ : String;
	@:require(flash10_1) static var STRING_SYSTEM : String;
	@:require(flash10_1) static var STRING_UNDO : String;
	@:require(flash10_1) static var STRING_UPARROW : String;
	@:require(flash10_1) static var STRING_USER : String;
	@:require(flash10_2) static var SUBTITLE : UInt;
	@:require(flash10_1) static var T : UInt;
	static var TAB : UInt;
	@:require(flash10_1) static var U : UInt;
	static var UP : UInt;
	@:require(flash10_1) static var V : UInt;
	@:require(flash10_2) static var VOD : UInt;
	@:require(flash10_1) static var W : UInt;
	@:require(flash10_1) static var X : UInt;
	@:require(flash10_1) static var Y : UInt;
	@:require(flash10_2) static var YELLOW : UInt;
	@:require(flash10_1) static var Z : UInt;
	static var capsLock(default,null) : Bool;
	@:require(flash10_1) static var hasVirtualKeyboard(default,null) : Bool;
	static var numLock(default,null) : Bool;
	@:require(flash10_1) static var physicalKeyboardType(default,null) : KeyboardType;
	static function isAccessible() : Bool;
}
#else



class Keyboard
{
   public static var A : Int = 65;
   public static var B : Int = 66;
   public static var C : Int = 67;
   public static var D : Int = 68;
   public static var E : Int = 69;
   public static var F : Int = 70;
   public static var G : Int = 71;
   public static var H : Int = 72;
   public static var I : Int = 73;
   public static var J : Int = 74;
   public static var K : Int = 75;
   public static var L : Int = 76;
   public static var M : Int = 77;
   public static var N : Int = 78;
   public static var O : Int = 79;
   public static var P : Int = 80;
   public static var Q : Int = 81;
   public static var R : Int = 82;
   public static var S : Int = 83;
   public static var T : Int = 84;
   public static var U : Int = 85;
   public static var V : Int = 86;
   public static var W : Int = 87;
   public static var X : Int = 88;
   public static var Y : Int = 89;
   public static var Z : Int = 90;

   public static var ALTERNATE : Int = 18;
   public static var BACKQUOTE : Int = 192;
   public static var BACKSLASH : Int = 220;
   public static var BACKSPACE : Int = 8;
   public static var CAPS_LOCK : Int = 20;
   public static var COMMA : Int = 188;
   public static var COMMAND : Int = 15;
   public static var CONTROL : Int = 17;
   public static var DELETE : Int = 46;
   public static var DOWN : Int = 40;
   public static var END : Int = 35;
   public static var ENTER : Int = 13;
   public static var EQUAL : Int = 187;
   public static var ESCAPE : Int = 27;
   public static var F1 : Int = 112;
   public static var F2 : Int = 113;
   public static var F3 : Int = 114;
   public static var F4 : Int = 115;
   public static var F5 : Int = 116;
   public static var F6 : Int = 117;
   public static var F7 : Int = 118;
   public static var F8 : Int = 119;
   public static var F9 : Int = 120;
   public static var F10 : Int = 121;
   public static var F11 : Int = 122;
   public static var F12 : Int = 123;
   public static var F13 : Int = 124;
   public static var F14 : Int = 125;
   public static var F15 : Int = 126;
   public static var HOME : Int = 36;
   public static var INSERT : Int = 45;
   public static var LEFT : Int = 37;
   public static var LEFTBRACKET : Int = 219;
   public static var MINUS : Int = 189;
   public static var NUMBER_0 : Int = 48;
   public static var NUMBER_1 : Int = 49;
   public static var NUMBER_2 : Int = 50;
   public static var NUMBER_3 : Int = 51;
   public static var NUMBER_4 : Int = 52;
   public static var NUMBER_5 : Int = 53;
   public static var NUMBER_6 : Int = 54;
   public static var NUMBER_7 : Int = 55;
   public static var NUMBER_8 : Int = 56;
   public static var NUMBER_9 : Int = 57;
   public static var NUMPAD : Int = 21;
   public static var NUMPAD_0 : Int = 96;
   public static var NUMPAD_1 : Int = 97;
   public static var NUMPAD_2 : Int = 98;
   public static var NUMPAD_3 : Int = 99;
   public static var NUMPAD_4 : Int = 100;
   public static var NUMPAD_5 : Int = 101;
   public static var NUMPAD_6 : Int = 102;
   public static var NUMPAD_7 : Int = 103;
   public static var NUMPAD_8 : Int = 104;
   public static var NUMPAD_9 : Int = 105;
   public static var NUMPAD_ADD : Int = 107;
   public static var NUMPAD_DECIMAL : Int = 110;
   public static var NUMPAD_DIVIDE : Int = 111;
   public static var NUMPAD_ENTER : Int = 108;
   public static var NUMPAD_MULTIPLY : Int = 106;
   public static var NUMPAD_SUBTRACT : Int = 109;
   public static var PAGE_DOWN : Int = 34;
   public static var PAGE_UP : Int = 33;
   public static var PERIOD : Int = 190;
   public static var QUOTE : Int = 222;
   public static var RIGHT : Int = 39;
   public static var RIGHTBRACKET : Int = 221;
   public static var SEMICOLON : Int = 186;
   public static var SHIFT : Int = 16;
   public static var SLASH : Int = 191;
   public static var SPACE : Int = 32;
   public static var TAB : Int = 9;
   public static var UP : Int = 38;

   //public static var capsLock(default,null) : Bool;
   //public static var numLock(default,null) : Bool;
   //public static function isAccessible() : Bool;
}
#end