package nme.ui;
#if code_completion


extern class Keyboard {
	@:require(flash10_1) static var A : Int;
	@:require(flash10_1) static var ALTERNATE : Int;
	//@:require(flash10_2) static var AUDIO : Int;
	@:require(flash10_1) static var B : Int;
	//@:require(flash10_2) static var BACK : Int;
	@:require(flash10_1) static var BACKQUOTE : Int;
	@:require(flash10_1) static var BACKSLASH : Int;
	static var BACKSPACE : Int;
	//@:require(flash10_2) static var BLUE : Int;
	@:require(flash10_1) static var C : Int;
	static var CAPS_LOCK : Int;
	//@:require(flash10_2) static var CHANNEL_DOWN : Int;
	//@:require(flash10_2) static var CHANNEL_UP : Int;
	@:require(flash10_1) static var COMMA : Int;
	@:require(flash10_1) static var COMMAND : Int;
	static var CONTROL : Int;
	//@:require(flash10_1) static var CharCodeStrings : Array<Dynamic>;
	@:require(flash10_1) static var D : Int;
	static var DELETE : Int;
	static var DOWN : Int;
	//@:require(flash10_2) static var DVR : Int;
	@:require(flash10_1) static var E : Int;
	static var END : Int;
	static var ENTER : Int;
	@:require(flash10_1) static var EQUAL : Int;
	static var ESCAPE : Int;
	//@:require(flash10_2) static var EXIT : Int;
	@:require(flash10_1) static var F : Int;
	static var F1 : Int;
	static var F10 : Int;
	static var F11 : Int;
	static var F12 : Int;
	static var F13 : Int;
	static var F14 : Int;
	static var F15 : Int;
	static var F2 : Int;
	static var F3 : Int;
	static var F4 : Int;
	static var F5 : Int;
	static var F6 : Int;
	static var F7 : Int;
	static var F8 : Int;
	static var F9 : Int;
	//@:require(flash10_2) static var FAST_FORWARD : Int;
	@:require(flash10_1) static var G : Int;
	//@:require(flash10_2) static var GREEN : Int;
	//@:require(flash10_2) static var GUIDE : Int;
	@:require(flash10_1) static var H : Int;
	//@:require(flash10_2) static var HELP : Int;
	static var HOME : Int;
	@:require(flash10_1) static var I : Int;
	//@:require(flash10_2) static var INFO : Int;
	//@:require(flash10_2) static var INPUT : Int;
	static var INSERT : Int;
	@:require(flash10_1) static var J : Int;
	@:require(flash10_1) static var K : Int;
	//@:require(flash10_1) static var KEYNAME_BEGIN : String;
	//@:require(flash10_1) static var KEYNAME_BREAK : String;
	//@:require(flash10_1) static var KEYNAME_CLEARDISPLAY : String;
	//@:require(flash10_1) static var KEYNAME_CLEARLINE : String;
	//@:require(flash10_1) static var KEYNAME_DELETE : String;
	//@:require(flash10_1) static var KEYNAME_DELETECHAR : String;
	//@:require(flash10_1) static var KEYNAME_DELETELINE : String;
	//@:require(flash10_1) static var KEYNAME_DOWNARROW : String;
	//@:require(flash10_1) static var KEYNAME_END : String;
	//@:require(flash10_1) static var KEYNAME_EXECUTE : String;
	//@:require(flash10_1) static var KEYNAME_F1 : String;
	//@:require(flash10_1) static var KEYNAME_F10 : String;
	//@:require(flash10_1) static var KEYNAME_F11 : String;
	//@:require(flash10_1) static var KEYNAME_F12 : String;
	//@:require(flash10_1) static var KEYNAME_F13 : String;
	//@:require(flash10_1) static var KEYNAME_F14 : String;
	//@:require(flash10_1) static var KEYNAME_F15 : String;
	//@:require(flash10_1) static var KEYNAME_F16 : String;
	//@:require(flash10_1) static var KEYNAME_F17 : String;
	//@:require(flash10_1) static var KEYNAME_F18 : String;
	//@:require(flash10_1) static var KEYNAME_F19 : String;
	//@:require(flash10_1) static var KEYNAME_F2 : String;
	//@:require(flash10_1) static var KEYNAME_F20 : String;
	//@:require(flash10_1) static var KEYNAME_F21 : String;
	//@:require(flash10_1) static var KEYNAME_F22 : String;
	//@:require(flash10_1) static var KEYNAME_F23 : String;
	//@:require(flash10_1) static var KEYNAME_F24 : String;
	//@:require(flash10_1) static var KEYNAME_F25 : String;
	//@:require(flash10_1) static var KEYNAME_F26 : String;
	//@:require(flash10_1) static var KEYNAME_F27 : String;
	//@:require(flash10_1) static var KEYNAME_F28 : String;
	//@:require(flash10_1) static var KEYNAME_F29 : String;
	//@:require(flash10_1) static var KEYNAME_F3 : String;
	//@:require(flash10_1) static var KEYNAME_F30 : String;
	//@:require(flash10_1) static var KEYNAME_F31 : String;
	//@:require(flash10_1) static var KEYNAME_F32 : String;
	//@:require(flash10_1) static var KEYNAME_F33 : String;
	//@:require(flash10_1) static var KEYNAME_F34 : String;
	//@:require(flash10_1) static var KEYNAME_F35 : String;
	//@:require(flash10_1) static var KEYNAME_F4 : String;
	//@:require(flash10_1) static var KEYNAME_F5 : String;
	//@:require(flash10_1) static var KEYNAME_F6 : String;
	//@:require(flash10_1) static var KEYNAME_F7 : String;
	//@:require(flash10_1) static var KEYNAME_F8 : String;
	//@:require(flash10_1) static var KEYNAME_F9 : String;
	//@:require(flash10_1) static var KEYNAME_FIND : String;
	//@:require(flash10_1) static var KEYNAME_HELP : String;
	//@:require(flash10_1) static var KEYNAME_HOME : String;
	//@:require(flash10_1) static var KEYNAME_INSERT : String;
	//@:require(flash10_1) static var KEYNAME_INSERTCHAR : String;
	//@:require(flash10_1) static var KEYNAME_INSERTLINE : String;
	//@:require(flash10_1) static var KEYNAME_LEFTARROW : String;
	//@:require(flash10_1) static var KEYNAME_MENU : String;
	//@:require(flash10_1) static var KEYNAME_MODESWITCH : String;
	//@:require(flash10_1) static var KEYNAME_NEXT : String;
	//@:require(flash10_1) static var KEYNAME_PAGEDOWN : String;
	//@:require(flash10_1) static var KEYNAME_PAGEUP : String;
	//@:require(flash10_1) static var KEYNAME_PAUSE : String;
	//@:require(flash10_1) static var KEYNAME_PREV : String;
	//@:require(flash10_1) static var KEYNAME_PRINT : String;
	//@:require(flash10_1) static var KEYNAME_PRINTSCREEN : String;
	//@:require(flash10_1) static var KEYNAME_REDO : String;
	//@:require(flash10_1) static var KEYNAME_RESET : String;
	//@:require(flash10_1) static var KEYNAME_RIGHTARROW : String;
	//@:require(flash10_1) static var KEYNAME_SCROLLLOCK : String;
	//@:require(flash10_1) static var KEYNAME_SELECT : String;
	//@:require(flash10_1) static var KEYNAME_STOP : String;
	//@:require(flash10_1) static var KEYNAME_SYSREQ : String;
	//@:require(flash10_1) static var KEYNAME_SYSTEM : String;
	//@:require(flash10_1) static var KEYNAME_UNDO : String;
	//@:require(flash10_1) static var KEYNAME_UPARROW : String;
	//@:require(flash10_1) static var KEYNAME_USER : String;
	@:require(flash10_1) static var L : Int;
	//@:require(flash10_2) static var LAST : Int;
	static var LEFT : Int;
	@:require(flash10_1) static var LEFTBRACKET : Int;
	//@:require(flash10_2) static var LIVE : Int;
	@:require(flash10_1) static var M : Int;
	//@:require(flash10_2) static var MASTER_SHELL : Int;
	//@:require(flash10_2) static var MENU : Int;
	@:require(flash10_1) static var MINUS : Int;
	@:require(flash10_1) static var N : Int;
	//@:require(flash10_2) static var NEXT : Int;
	@:require(flash10_1) static var NUMBER_0 : Int;
	@:require(flash10_1) static var NUMBER_1 : Int;
	@:require(flash10_1) static var NUMBER_2 : Int;
	@:require(flash10_1) static var NUMBER_3 : Int;
	@:require(flash10_1) static var NUMBER_4 : Int;
	@:require(flash10_1) static var NUMBER_5 : Int;
	@:require(flash10_1) static var NUMBER_6 : Int;
	@:require(flash10_1) static var NUMBER_7 : Int;
	@:require(flash10_1) static var NUMBER_8 : Int;
	@:require(flash10_1) static var NUMBER_9 : Int;
	@:require(flash10_1) static var NUMPAD : Int;
	static var NUMPAD_0 : Int;
	static var NUMPAD_1 : Int;
	static var NUMPAD_2 : Int;
	static var NUMPAD_3 : Int;
	static var NUMPAD_4 : Int;
	static var NUMPAD_5 : Int;
	static var NUMPAD_6 : Int;
	static var NUMPAD_7 : Int;
	static var NUMPAD_8 : Int;
	static var NUMPAD_9 : Int;
	static var NUMPAD_ADD : Int;
	static var NUMPAD_DECIMAL : Int;
	static var NUMPAD_DIVIDE : Int;
	static var NUMPAD_ENTER : Int;
	static var NUMPAD_MULTIPLY : Int;
	static var NUMPAD_SUBTRACT : Int;
	@:require(flash10_1) static var O : Int;
	@:require(flash10_1) static var P : Int;
	static var PAGE_DOWN : Int;
	static var PAGE_UP : Int;
	//@:require(flash10_2) static var PAUSE : Int;
	@:require(flash10_1) static var PERIOD : Int;
	//@:require(flash10_2) static var PLAY : Int;
	//@:require(flash10_2) static var PREVIOUS : Int;
	@:require(flash10_1) static var Q : Int;
	@:require(flash10_1) static var QUOTE : Int;
	@:require(flash10_1) static var R : Int;
	//@:require(flash10_2) static var RECORD : Int;
	//@:require(flash10_2) static var RED : Int;
	//@:require(flash10_2) static var REWIND : Int;
	static var RIGHT : Int;
	@:require(flash10_1) static var RIGHTBRACKET : Int;
	@:require(flash10_1) static var S : Int;
	//@:require(flash10_2) static var SEARCH : Int;
	@:require(flash10_1) static var SEMICOLON : Int;
	@:require(flash10_2) static var SETUP : Int;
	static var SHIFT : Int;
	//@:require(flash10_2) static var SKIP_BACKWARD : Int;
	//@:require(flash10_2) static var SKIP_FORWARD : Int;
	@:require(flash10_1) static var SLASH : Int;
	static var SPACE : Int;
	//@:require(flash10_2) static var STOP : Int;
	//@:require(flash10_1) static var STRING_BEGIN : String;
	//@:require(flash10_1) static var STRING_BREAK : String;
	//@:require(flash10_1) static var STRING_CLEARDISPLAY : String;
	//@:require(flash10_1) static var STRING_CLEARLINE : String;
	//@:require(flash10_1) static var STRING_DELETE : String;
	//@:require(flash10_1) static var STRING_DELETECHAR : String;
	//@:require(flash10_1) static var STRING_DELETELINE : String;
	//@:require(flash10_1) static var STRING_DOWNARROW : String;
	//@:require(flash10_1) static var STRING_END : String;
	//@:require(flash10_1) static var STRING_EXECUTE : String;
	//@:require(flash10_1) static var STRING_F1 : String;
	//@:require(flash10_1) static var STRING_F10 : String;
	//@:require(flash10_1) static var STRING_F11 : String;
	//@:require(flash10_1) static var STRING_F12 : String;
	//@:require(flash10_1) static var STRING_F13 : String;
	//@:require(flash10_1) static var STRING_F14 : String;
	//@:require(flash10_1) static var STRING_F15 : String;
	//@:require(flash10_1) static var STRING_F16 : String;
	//@:require(flash10_1) static var STRING_F17 : String;
	//@:require(flash10_1) static var STRING_F18 : String;
	//@:require(flash10_1) static var STRING_F19 : String;
	//@:require(flash10_1) static var STRING_F2 : String;
	//@:require(flash10_1) static var STRING_F20 : String;
	//@:require(flash10_1) static var STRING_F21 : String;
	//@:require(flash10_1) static var STRING_F22 : String;
	//@:require(flash10_1) static var STRING_F23 : String;
	//@:require(flash10_1) static var STRING_F24 : String;
	//@:require(flash10_1) static var STRING_F25 : String;
	//@:require(flash10_1) static var STRING_F26 : String;
	//@:require(flash10_1) static var STRING_F27 : String;
	//@:require(flash10_1) static var STRING_F28 : String;
	//@:require(flash10_1) static var STRING_F29 : String;
	//@:require(flash10_1) static var STRING_F3 : String;
	//@:require(flash10_1) static var STRING_F30 : String;
	//@:require(flash10_1) static var STRING_F31 : String;
	//@:require(flash10_1) static var STRING_F32 : String;
	//@:require(flash10_1) static var STRING_F33 : String;
	//@:require(flash10_1) static var STRING_F34 : String;
	//@:require(flash10_1) static var STRING_F35 : String;
	//@:require(flash10_1) static var STRING_F4 : String;
	//@:require(flash10_1) static var STRING_F5 : String;
	//@:require(flash10_1) static var STRING_F6 : String;
	//@:require(flash10_1) static var STRING_F7 : String;
	//@:require(flash10_1) static var STRING_F8 : String;
	//@:require(flash10_1) static var STRING_F9 : String;
	//@:require(flash10_1) static var STRING_FIND : String;
	//@:require(flash10_1) static var STRING_HELP : String;
	//@:require(flash10_1) static var STRING_HOME : String;
	//@:require(flash10_1) static var STRING_INSERT : String;
	//@:require(flash10_1) static var STRING_INSERTCHAR : String;
	//@:require(flash10_1) static var STRING_INSERTLINE : String;
	//@:require(flash10_1) static var STRING_LEFTARROW : String;
	//@:require(flash10_1) static var STRING_MENU : String;
	//@:require(flash10_1) static var STRING_MODESWITCH : String;
	//@:require(flash10_1) static var STRING_NEXT : String;
	//@:require(flash10_1) static var STRING_PAGEDOWN : String;
	//@:require(flash10_1) static var STRING_PAGEUP : String;
	//@:require(flash10_1) static var STRING_PAUSE : String;
	//@:require(flash10_1) static var STRING_PREV : String;
	//@:require(flash10_1) static var STRING_PRINT : String;
	//@:require(flash10_1) static var STRING_PRINTSCREEN : String;
	//@:require(flash10_1) static var STRING_REDO : String;
	//@:require(flash10_1) static var STRING_RESET : String;
	//@:require(flash10_1) static var STRING_RIGHTARROW : String;
	//@:require(flash10_1) static var STRING_SCROLLLOCK : String;
	//@:require(flash10_1) static var STRING_SELECT : String;
	//@:require(flash10_1) static var STRING_STOP : String;
	//@:require(flash10_1) static var STRING_SYSREQ : String;
	//@:require(flash10_1) static var STRING_SYSTEM : String;
	//@:require(flash10_1) static var STRING_UNDO : String;
	//@:require(flash10_1) static var STRING_UPARROW : String;
	//@:require(flash10_1) static var STRING_USER : String;
	//@:require(flash10_2) static var SUBTITLE : Int;
	@:require(flash10_1) static var T : Int;
	static var TAB : Int;
	@:require(flash10_1) static var U : Int;
	static var UP : Int;
	@:require(flash10_1) static var V : Int;
	//@:require(flash10_2) static var VOD : Int;
	@:require(flash10_1) static var W : Int;
	@:require(flash10_1) static var X : Int;
	@:require(flash10_1) static var Y : Int;
	//@:require(flash10_2) static var YELLOW : Int;
	@:require(flash10_1) static var Z : Int;
	//static var capsLock(default,null) : Bool;
	//@:require(flash10_1) static var hasVirtualKeyboard(default,null) : Bool;
	//static var numLock(default,null) : Bool;
	//@:require(flash10_1) static var physicalKeyboardType(default,null) : KeyboardType;
	//static function isAccessible() : Bool;
}


#elseif (cpp || neko)
typedef Keyboard = neash.ui.Keyboard;
#elseif js
typedef Keyboard = jeash.ui.Keyboard;
#else
typedef Keyboard = flash.ui.Keyboard;
#end